CodebenderBuilderBundle_status_check:
    path:  /status
    defaults: { _controller: CodebenderBuilderBundle:Default:status }

CodebenderBuilderBundle_handle_request:
    path:    /{authKey}/{version}/
    defaults: { _controller: CodebenderBuilderBundle:Default:handleRequest }
    methods: [POST]

CodebenderBuilderBundle_ganerate_compiler_payload:
    path:    /{authKey}/{version}/payload
    defaults: { _controller: CodebenderBuilderBundle:Default:generatePayload }
    methods: [POST]